config/routes.rb
Rails.application.routes.draw do
  post 'feedbacks/create'
  root 'products#index'
  get 'comments/index'
  get 'comments/new'
  devise_for :users
  resources :users do
    resources :comments
    collection do
      get :pending_approval
      get '/approve/:id', to: 'users#approve', as: 'approve'
      get '/refuse/:id', to: 'users#refuse', as: 'refuse'
    end
  end
  resources :products do
    resources :comments
  end
  resources :details
  resources :likes
  get "details/pay/:id", to: 'details#pay', as: 'pay'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  # get '/products/:id', to: 'products#show', as: 'products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role
  has_many :purchases
  has_many :likes
  has_many :products, through: :likes
  has_many :comments, as: :commentable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def assign_default_role
     self.add_role(:client) if self.roles.blank?
   end

  def admin?
    has_role?(:admin)
  end

  def client?
    has_role?(:client)
  end

end

app/controllers/api/v1/users_controller.rb
module API
  module V1
    class UsersController < ApplicationController
      SECRET_KEY = '0ef0a696-67a1-4987-83e4-4cbc3d0c20e8' # this is wrong in so many levels
      skip_before_action :verify_authenticity_token

      def index
        token = request.headers["token"]
        begin
          decoded_token = JWT.decode token, SECRET_KEY, true, { algorithm: 'HS256' }
          user = User.find(decoded_token[0]['user_id'])
          render json: {status: 'FOUND', message: 'User found', user: user}, status: :found
        rescue ActiveRecord::RecordNotFound
          render json: {status: 'NOT FOUND', message: 'User not found'}, status: :not_found
        rescue JWT::VerificationError
          render json: {status: 'UNAUTHORIZED', message: 'Signature has expired'}, status: :unauthorized
        rescue StandardError
          render json: {status: 'NOT FOUND', message: 'User not found'}, status: :conflict
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_comment, only: %i[approve refuse]
  before_action :check_login_admin, only: %i[pending_approval approve refuse]
  before_action :check_login, only: %i[index show]

  def index
    @users = User.with_role :client
  end

  def show
    @user = User.find(params[:id])
    redirect_to users_path if @user.has_role? :admin
    @commentable = @user
    @comments = @commentable.comments.approve
    @comment = Comment.new
    # @feedback = Feedback.new
  end

  def pending_approval
    @review_pending = Comment.type_user
  end

  def approve; end

  def refuse; end

  private

  def set_comment
    @comment = Comment.find(params[:id])
    if action_name == 'approve'
      @comment.state = 1
    else
      @comment.state = 0
    end
    @comment.save
    redirect_to pending_approval_users_path
  end

  def check_login_admin
    unless user_signed_in? && (current_user.has_role? :admin)
      redirect_to products_path and return
    end
  end

  def check_login
    unless user_signed_in?
      redirect_to products_path and return
    end
  end
end

app/views/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">User Name</th>
      <th scope="col">Email</th>
      <th scope="col">View Profile</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u|%>
      <% unless u.id == current_user.id%>
        <tr>
          <td><%= u.username %></td>
          <td><%= u.email %></td>
          <td><%= link_to "View Profile", user_path(u.id), class: "btn btn-success" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/pending_approval.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">User Profile</th>
      <th scope="col">User Review</th>
      <th scope="col">Review</th>
      <th scope="col">Date</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @review_pending.each do |re|%>
      <tr>
        <td><%= re.commentable.username %></td>
        <td><%= re.user.username %></td>
        <td><%= re.review %></td>
        <td><%= re.created_at.getlocal.strftime("%m/%d/%Y %I:%M %p") %></td>
        <td>
          <%= link_to "View Profile", user_path(re.commentable_id), class: "btn btn-info" %>
          <% if re.state == 0%>
            <%= link_to "Show", approve_users_path(re.id), class: "btn btn-success" %>
          <% else %>
            <%= link_to "Hide", refuse_users_path(re.id), class: "btn btn-warning" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="panel panel-default col-md-6" align = "center">
  <div class="panel-body">
    <h1>User Profile</h1>
    <label>Name User:</label>
    <label> <%= @user.username %> </label></br>
    <label>Email:</label>
    <label> <%= @user.email %> </label></br>
    <label>Average Feedback:</label>
    <label> <%= @user.comments.where(state: 1).average(:score) %> </label></br></br>

  </div>
</div>


  <div class="panel panel-default col-md-6">
    <div class="panel-body">
      <h3>Comments</h3>
      <%= render "comments/comments" %>
<% if (current_user.id != @user.id) and (current_user.has_role? :client) %>
      <h3>Add Comment</h3>
      <%= render "comments/form" %>
    </div>
  </div>
<% end %>