config/routes.rb
Rails.application.routes.draw do
  post 'feedbacks/create'
  root 'products#index'
  get 'comments/index'
  get 'comments/new'
  devise_for :users
  resources :users do
    resources :comments
    collection do
      get :pending_approval
      get '/approve/:id', to: 'users#approve', as: 'approve'
      get '/refuse/:id', to: 'users#refuse', as: 'refuse'
    end
  end
  resources :products do
    resources :comments
  end
  resources :details
  resources :likes
  get "details/pay/:id", to: 'details#pay', as: 'pay'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  # get '/products/:id', to: 'products#show', as: 'products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :details
  has_many :purchases, through: :details
  has_many :likes
  has_many :users, through: :likes
  has_many :comments, as: :commentable
  has_and_belongs_to_many :tags
  has_one_attached :image
  validates :sku, uniqueness: true


  scope :available, -> { where(state: 1) }
  scope :name_like, ->(product_name) { where('name ILIKE ?', "%#{product_name}%") }
  scope :order_by_name, -> { order(name: :ASC) }

  delegate :name, to: :category, prefix: true


  def product_image
    return self.image.variant(resize: '220x220').processed
  end
end

app/controllers/api/v1/products_controller.rb
module API
  module V1
    class ProductsController < ApplicationController
      include Pagy::Backend
      # respond_to :json

      def index
        products =
          if params[:search].present? && params[:search][:name]
            Product.name_like(params[:search][:name]).order_by_name
          else
            Product.all.order_by_name
          end
        product = pagy(products, items: 10)
        render json: {status: 'SUCCESS', message: 'Loaded products', data: product},status: :ok
        # respond_with product
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagy::Backend
  before_action :set_category, only: %i[index new edit]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :check_login, except: %i[index show]

  def index
    @like = Like.new
    @search = OpenStruct.new(
      params.fetch(:search, {}))
    @products =
      if params[:search].present?
        Product.available.name_like(params[:search][:name])
      else
        Product.available.all.order_by_name
      end
    @pagy, @product = pagy(@products, items: 10)
  end

  def show
    @commentable = @product
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    product.state = 1
    product.save
    redirect_to products_path
  end

  def edit; end

  def update
    @product.assign_attributes(product_params)
    if @product.save
      redirect_to products_path and return
    else
      render 'edit'
    end
  end

  def destroy
    @product.state = 0
    @product.save
    redirect_to products_path and return
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :stock, :sku, :category_id, :image)
  end

  def set_category
    @categories = Category.all.order_by_name
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def check_login
    unless user_signed_in? && (current_user.has_role? :admin)
      redirect_to products_path and return
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  include Pagy::Frontend

end

app/views/products/edit.html.erb
<h1> Edit Product </h1>
<%= form_for @product do |f| %>
    <div class="form-group">
      <p><%= label_tag 'Name' %></p>
      <p><%= f.text_field :name, placeholder: 'Product name', class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Price' %></p>
      <p><%= f.text_field :price, placeholder: 'Product Price', class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Stock' %></p>
      <p><%= f.text_field :stock, placeholder: 'Product Stock', class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Sku' %></p>
      <p><%= f.text_field :sku, placeholder: 'Product Sku', class: 'form-control', readonly: true %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Category' %></p>
      <p><%= f.select :category_id, @categories.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Image' %></p>
      <p><%= f.file_field :image%></p>
    </div>
    <%= link_to products_path, class: "btn btn-info" do %>
      Back
   <% end %>
   <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/products/index.html.erb
<div class="container">
  <% if user_signed_in? %>
  <div class="container" align = "right">
    <% if current_user and current_user.has_role? :client %>
      <%= link_to "Cart", detail_path(current_user.id), method: :get, class: "btn btn-info" %>
    <% end %>
    <% if current_user and current_user.has_role? :admin %>
      <%= link_to "New Product", new_product_path, class: "btn btn-info" %>
    <% end %>
  <%end%>
  </div>

  <h2 align='center'>Welcome to store</h2>
  <div class="container" align = "center">
    <%= form_for @search, url: products_path, as: :search,  method: :get do |f| %>
       <%= f.select :sort, [["Name","name ASC"], ["Likes","likes_count ASC"]] %>
       <%= f.select :category_id, @categories.collect {|p| [ p.name, p.id ] }, { include_blank: true } %>
       <%= f.text_field :name %>
       <%= link_to products_path, class: 'btn btn-warning' do %>
        Clear
       <% end %>
       <%= f.submit "Search", class: 'btn btn-success' %>
    <% end %>
  </div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">SKU</th>
        <th scope="col">Name</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">Stock</th>
        <% if user_signed_in? %>
          <th scope="col">Show</th>
          <!-- Repetition much? I told you about this in week 5! -->
        <% if current_user and current_user.has_role? :client %>
          <th scope="col">Like</th>
          <th scope="col">Num Likes</th>
        <% end %>
          <% if current_user and current_user.has_role? :admin %>
            <th>Options</th>
          <% end %>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @product.each_with_index do |product, index|%>
      <tr>
        <th scope="row"> <%= index+1%> </th>
        <td> <%= product.sku%> </td>
        <td> <%= product.name%> </td>
        <td> <%= product.category_name%> </td>
        <td> <%= product.price%> </td>
        <td> <%= product.stock%> </td>
        <% if user_signed_in? %>
          <td><%= link_to "Show Product", product_path(product.id), class: "btn btn-success" %></td>
          <% if current_user and current_user.has_role? :client %>
            <td>
              <%= form_with model: @like, method: "post" do |f| %>
                <%= f.hidden_field :product_id, value: product.id %>
                <%= f.submit "LIKE", class: "btn btn-info" %>
              <% end %>
            </td>
            <td><%= product.likes.size %></td>
          <% end %>
          <% if current_user and current_user.has_role? :admin %>
            <td>
              <%= link_to 'edit', edit_product_path(product.id), class: "btn btn-info" %>
              <%= link_to 'Delete', product_path(product), method: :delete, class: "btn btn-warning", data: {confirm: "Are you sure?"} %>
            </td>
          <% end %>
        <%end%>

      </tr>
      <% end %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/products/new.html.erb
<h1> New Product </h1>
<%= form_for @product do |f| %>
    <div class="form-group">
      <p><%= label_tag 'Name' %></p>
      <p><%= f.text_field :name, placeholder: 'Product name', class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Price' %></p>
      <p><%= f.text_field :price, placeholder: 'Product Price', class: 'form-control', type: "number" %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Stock' %></p>
      <p><%= f.text_field :stock, placeholder: 'Product Stock', class: 'form-control', type: "number" %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Sku' %></p>
      <p><%= f.text_field :sku, value: Faker::Number.hexadecimal, placeholder: 'Product Sku', class: 'form-control', readonly: true %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Category' %></p>
      <p><%= f.select :category_id, @categories.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: 'form-control' %></p>
    </div>
    <div class="form-group">
      <p><%= label_tag 'Image' %></p>
      <p><%= f.file_field :image%></p>
    </div>
    <%= link_to products_path, class: "btn btn-info" do %>
      Back
   <% end %>
   <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/products/show.html.erb
<div class="panel panel-default col-md-6" align = "center">
  <div class="panel-body">
    <h1>Product Detail</h1>
    <% if @product.image.attached? %>
      <%= image_tag @product.product_image %> </label></br></br>
    <% end %>
    <label>Name:</label>
    <label> <%= @product.name%> </label></br>
    <label>Category:</label>
    <label> <%= @product.category_name%> </label></br>
    <label>Quantity Available:</label>
    <label> <%= @product.stock%> </label></br>
    <label>Rating:</label>
    <!-- Don't you have a scope for this? -->
    <label> <%= @product.comments.where(state: 1).average(:score) %> </label>
    <h3>Price: $<%=@product.price%></h3>
    <% if current_user and current_user.has_role? :client %>
      <%= form_for(Detail.new) do |f| %>
          <%= label_tag :quantity %>
          <%= f.select :quantity, (1..@product.stock) %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.submit "Add Cart" %>
      <% end %>
    <% end %>
  </div>
</div>
<% if current_user and current_user.has_role? :client %>
    <div class="panel panel-default col-md-6">
      <div class="panel-body">
        <h3>Comments</h3>

        <%= render "comments/comments" %>
        <h3>Add Comment</h3>
        <%= render "comments/form" %>
      </div>
    </div>
<% end %>