config/routes.rb
Rails.application.routes.draw do
  post 'feedbacks/create'
  root 'products#index'
  get 'comments/index'
  get 'comments/new'
  devise_for :users
  resources :users do
    resources :comments
    collection do
      get :pending_approval
      get '/approve/:id', to: 'users#approve', as: 'approve'
      get '/refuse/:id', to: 'users#refuse', as: 'refuse'
    end
  end
  resources :products do
    resources :comments
  end
  resources :details
  resources :likes
  get "details/pay/:id", to: 'details#pay', as: 'pay'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  # get '/products/:id', to: 'products#show', as: 'products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :product
  belongs_to :purchase

  delegate :name, :sku, :price, :category_name, to: :product, prefix: true

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  before_action :set_purchase, only: %i[create show]
  before_action :check_login
  def create
    unless @purchase
      @purchase = Purchase.new(user_id: current_user.id, state: 1)
      @purchase.save
    end
    update_stock(detail_params[:product_id], detail_params[:quantity].to_i)
    detail = @purchase.details.find_by(product_id: detail_params[:product_id])
    if detail
      detail.quantity += detail_params[:quantity].to_i
      detail.save
    else
      @purchase.details.create(detail_params)
    end
    redirect_to products_path
  end

  def show
    @details = @purchase.details if @purchase
  end

  def pay
    purchase = Purchase.find(params[:id])
    purchase.state = 0
    purchase.save
    redirect_to products_path and return
  end

  private

  def detail_params
    params.require(:detail).permit(:product_id, :quantity)
  end

  def set_purchase
    @purchase = current_user.purchases.find_by(state: 1)
  end

  def check_login
    unless user_signed_in? && (current_user.has_role? :client)
      redirect_to products_path and return
    end
  end

  def update_stock(product_id, quantity)
    product = Product.find(product_id)
    product.stock = product.stock - quantity
    product.save

    if product.likes.any? && product.stock <= 3
      SendNotificationsJob.perform_later(product)
    end
  end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<script src="https://use.fontawesome.com/c560c025cf.js"></script>
<div class="container">
  <% if @purchase %>
  <div class="container">
   <div class="card shopping-cart">
            <div class="card-header bg-dark text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Shipping cart
                <a href="/" class="btn btn-outline-info btn-sm pull-right">Continiu shopping</a>
                <div class="clearfix"></div>
            </div>
            <div class="card-body">
                    <!-- PRODUCT -->
                    <% @total = 0 %>
                    <% @details.each do |detail|%>
                    <div class="row">
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-2">
                            <h4 class="product-name">SKU:   <strong><%= detail.product_sku %></strong></h4>
                            <h4>
                                <small></small>
                            </h4>
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-4">
                            <h4 class="product-name"><strong><%= detail.product_name %></strong></h4>
                            <h4>
                                <small><%= detail.product_category_name %></small>
                            </h4>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-6 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-5 text-md-right" style="padding-top: 5px">
                                <h4><strong><%= detail.product_price %><span class="text-muted"> x</span></strong></h4>
                            </div>
                            <div class="col-3 col-sm-3 col-md-5 text-md-right" style="padding-top: 5px">
                                <h4><strong><%= detail.quantity %><span class="text-muted"></span></strong></h4>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <h4><strong>$ <%= detail.product_price * detail.quantity %><span class="text-muted"></span></strong></h4>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <% @total = @total + detail.product_price * detail.quantity %>
                    <% end %>

                    <!-- END PRODUCT -->
            </div>
            <div class="card-footer">
                <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">

                </div>
                <div class="pull-right" style="margin: 10px">
                    <%=link_to "Pay Account", pay_path(@purchase), class: "btn btn-success pull-right"%>
                    <div class="pull-right" style="margin: 5px">
                        Total price: <h4>$ <%= @total %></h4>
                    </div>
                </div>
            </div>
        </div>
      </div>
  <%else%>
    <h1>Add products to cart for buy</h1>
  <%end%>
</div>